// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC28peJ0lgtmCeNda0vTpyX-NO0TsWMEAE',
    appId: '1:1079101724256:web:6f16c2a0e9c35fe20ed505',
    messagingSenderId: '1079101724256',
    projectId: 'lesson-68-ad1df',
    authDomain: 'lesson-68-ad1df.firebaseapp.com',
    storageBucket: 'lesson-68-ad1df.appspot.com',
    measurementId: 'G-0RDZYS21S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0S7FAyTVobrxEHtT6cVovx0Op6IKgzek',
    appId: '1:1079101724256:android:40670d6ad6f4dd170ed505',
    messagingSenderId: '1079101724256',
    projectId: 'lesson-68-ad1df',
    storageBucket: 'lesson-68-ad1df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFzy3oBSNE-utuoVA92cxiKBx2asPsupg',
    appId: '1:1079101724256:ios:5ecce0bbb1efae240ed505',
    messagingSenderId: '1079101724256',
    projectId: 'lesson-68-ad1df',
    storageBucket: 'lesson-68-ad1df.appspot.com',
    iosBundleId: 'com.example.lesson68',
  );

}